name: "Build linbo-gui build docker image"

on:
  push:
    branches:
      - master
    paths:
      - 'build/docker/**'
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    name: Build and push linbo-gui build Docker image to GhCr
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: build/docker
          push: true
          file: build/docker/Dockerfile
          tags: |
            ghcr.io/linuxmuster/linuxmuster-linbo-gui-build:latest
